spring.application.name=s5-crud
spring.jpa.hibernate.ddl-auto=update
spring.datasource.dbcp2.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/fsad-s5
spring.datasource.username=root
spring.datasource.password=venki1234
spring.jpa.show-sql=true