spring.application.name=s5-crud
spring.jpa.hibernate.ddl-auto=update
spring.datasource.dbcp2.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://hopper.proxy.rlwy.net:10468/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=RfRTGPeuTzmAuyKvSNHdpYESBPGuvpop
spring.jpa.show-sql=true
server.port=${PORT:8080}
